spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DATABASE:icodesoft}?zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  data:
    redis:
      host: localhost
      port: 6379
      password: a1c5a32428604289b4015d3aa196677e
  jpa:
    open-in-view: false #禁用 spring.jpa.open-in-view 后，必须在会话（事务）内完成所有数据加载工作，否则会遇到 LazyInitializationException
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080
